wasp-lang/open-saas

- app/.prettierrc
- app/main.wasp
- app/src/client/app/DemoAppPage.tsx
- Added icon for deletion of Task + Lucide Icons pack for other uses 
- Changed behaviour so Task can be deleted at all times 
- Adding Task when pressing Enter key
- Small colour fixes
> new icons, demo app improvement

- app/main.wasp
- app/src/client/app/DemoAppPage.tsx
- app/src/client/components/AppNavBar.tsx
- app/src/client/landing-page/LandingPage.tsx
- added dark mode for app menu
- organised sidebar into one component (AppNavBar) and used it in Landing page instead of same code
- changed colour of hamburger menu icon on dark mode
> added dark mode for sidebar/mobile menu

- README.md
- app/src/client/app/AccountPage.tsx
I was browsing the demo app and noticed the dark theme had an issue on the Account page for the two dynamic fields.
> Spotted small issues

- app/src/client/app/CheckoutPage.tsx
Fixes Issue #33. Added black text next to the white background where the message is shown, as seen on the screenshot
Also, Prettier added the semicolons on the end of the lines 18 and 19, based on the project's configuration.
> Fixed white text on dark mode on Checkout page

- blog/src/content/docs/start/getting-started.md
Created a description that helps Windows users use Wasp.
> Updated getting started guide to help Windows users.

- README.md
fix broken link to docs for Jobs 🚀
> fix broken docs link for Jobs

- app/tsconfig.json
Applies the changes from this PR: https://github.com/wasp-lang/wasp/pull/1921
> Update tsconfig.json to autocomplete imports

- blog/src/content/docs/start/getting-started.md
A couple of small fixes, let's see which ones we want to keep.
> Small updates to getting-started.md

- opensaas-sh/tools/dope.sh
Fixed the bug + added some general comments to make code easier to understand (it is bash, at the end).
> Fixed bug in dope.sh with not generating diffs for gitignored base files.

- template/app/.gitignore
No updates needed to the demo app.
> Updated .gitignore to the new, better version that will be coming with new Wasp soon.

- .github/workflows/e2e-tests.yml
- template/e2e-tests/tests/landingPageTests.spec.ts
tests were failing for cookie banner check https://github.com/wasp-lang/open-saas/issues/174
> avoid cookie setting race condition

- opensaas-sh/app_diff/src/client/auth/LoginPage.tsx.diff
- template/app/src/client/auth/LoginPage.tsx
https://github.com/wasp-lang/open-saas/issues/180
> Remove redirecting logged in user on Login page

- template/app/src/server/auth/setUsername.ts
https://github.com/wasp-lang/open-saas/issues/159
> add zod checks to social auth user field getters

- template/app/.env.server.example
fixes https://github.com/wasp-lang/open-saas/issues/79
> fix typo in plausible base url

- opensaas-sh/README.md
https://github.com/wasp-lang/open-saas/issues/164
> improve app_diff instructions on mac 

- template/app/main.wasp
- template/app/src/server/scripts/dbSeeds.ts
https://github.com/wasp-lang/open-saas/issues/146
> clean up db seeding file

- .github/workflows/e2e-tests.yml
- opensaas-sh/tools/dope.sh
Resolves https://github.com/wasp-lang/open-saas/issues/201
> Added check for demo app patching to CI.

- opensaas-sh/app_diff/main.wasp.diff
- opensaas-sh/app_diff/src/client/landing-page/LandingPage.tsx.diff
- opensaas-sh/app_diff/src/user/operations.ts.diff
- opensaas-sh/blog/src/content/docs/guides/authorization.md
- opensaas-sh/blog/src/content/docs/guides/stripe-integration.md
- opensaas-sh/blog/src/content/docs/start/guided-tour.md
- template/app/main.wasp
- template/app/src/client/admin/components/Header.tsx
- template/app/src/client/components/AppNavBar.tsx
- template/app/src/client/landing-page/LandingPage.tsx
- template/app/src/server/actions.ts
- template/app/src/server/queries.ts
- template/app/src/user/AccountPage.tsx
- template/app/src/user/DropdownUser.tsx
- template/app/src/user/UserMenuItems.tsx
- template/app/src/user/operations.ts
> Vertical user

- opensaas-sh/blog/src/content/docs/general/user-overview.md
- opensaas-sh/blog/src/content/docs/start/guided-tour.md
Fixing typos in the guided tour & user overview pages.
Moved from: https://github.com/wasp-lang/open-saas/pull/223
> Update user-overview.md & guided-tour.md fixing typos

- opensaas-sh/blog/src/content/docs/guides/seo.md
> docs: update seo.md

- opensaas-sh/app_diff/src/landing-page/contentSections.ts.diff
- opensaas-sh/blog/astro.config.mjs
- opensaas-sh/blog/src/content/docs/guides/tests.md
- template/e2e-tests/README.md
Adds a `tests` guide to the docs which includes a note about github workflows and changing the `WASP_VERSION` variable in the github action
> Add test docs

- template/app/src/user/AccountPage.tsx
**Issue**:  #118 
**Description**:
This PR fixes the missing margin on the logout button for smaller devices' account page. The margin was added to ensure consistent styling across different screen sizes.
**Screenshots**:
_Before:_
_After:_
**Testing**:
- Verified the logout button displays correctly on various mobile devices using browser developer tools.
- Ensured no other elements were affected by the change.
**Additional Notes**:
- Please review the changes and let me know if any adjustments are needed.
> Fixed logout button style on mobile responsive.

- template/app/tailwind.config.cjs
There is a duplicated dependency in the Tailwind config file.
> Fix - remove duplicated dependency at Tailwind config file

- MOST-ANNOYING-COOKIE-BANNER.md
My submission for the **MOST-ANNOYING-COOKIE-BANNER Hackathon**
> Updated MOST-ANNOYING-COOKIE-BANNER.md

- template/app/src/admin/dashboards/analytics/AnalyticsDashboardPage.tsx
- template/app/src/admin/dashboards/analytics/SourcesTable.tsx
> fix ublock extension blocking open saas

- template/app/src/demo-ai-app/DemoAppPage.tsx
Disabled the button to add task on DemoAppPage.tsx if there is no description. Updated the button styles to remove hover effects if disabled
> disabled button to add task if there is no description

- template/app/src/analytics/stats.ts
After uncommenting a line with the Google Analytics provider, I found the missing single quote character.  It's small but you got to start somewhere ;) I hope that this is not my last contribution to this amazing project!
> Add missing closing single quote character in commented line of code

- opensaas-sh/app_diff/main.wasp.diff
- opensaas-sh/app_diff/package-lock.json.diff
- opensaas-sh/blog/src/content/docs/general/admin-dashboard.mdx
- opensaas-sh/blog/src/content/docs/general/user-overview.md
- opensaas-sh/blog/src/content/docs/guides/analytics.md
- opensaas-sh/blog/src/content/docs/guides/authentication.md
- opensaas-sh/blog/src/content/docs/guides/authorization.md
- opensaas-sh/blog/src/content/docs/guides/cookie-consent.mdx
- opensaas-sh/blog/src/content/docs/guides/deploying.mdx
- opensaas-sh/blog/src/content/docs/guides/email-sending.mdx
- opensaas-sh/blog/src/content/docs/guides/file-uploading.mdx
- opensaas-sh/blog/src/content/docs/guides/payments-integration.mdx
- opensaas-sh/blog/src/content/docs/guides/seo.mdx
- opensaas-sh/blog/src/content/docs/guides/tests.md
- opensaas-sh/blog/src/content/docs/index.mdx
- opensaas-sh/blog/src/content/docs/start/getting-started.mdx
- opensaas-sh/blog/src/content/docs/start/guided-tour.md
- template/app/.cursorrules
- template/app/main.wasp
- template/app/tsconfig.json
> Upgrade v0.16

- opensaas-sh/blog/src/content/docs/blog/2025-02-27-meet-marko-saric-co-founder-of-privacy-friendly-plausible-analytics.mdx
> add an interactive demo to plausible post

- template/app/src/demo-ai-app/operations.ts
Fixes #401 by updating and deleting task where userId === context.user.id
- [] **Update e2e tests**: If you changed the [/template/app](/template/app), then make sure to do any neccessary updates to [/template/e2e-tests](/template/e2e-tests) also.
> Make Task Operations Great Again (aka more secure)

- opensaas-sh/blog/src/content/docs/guides/authentication.md
Just a quick fix for a broken link I stumbled upon while reading the docs.
> Fix broken discord auth link

- .editorconfig
- .gitignore
- .prettierignore
- .prettierrc
- opensaas-sh/app_diff/.gitignore.diff
- package-lock.json
- package.json
- template/.gitignore
- template/app/.gitignore
- template/blog/.gitignore
- template/e2e-tests/.gitignore
This is NOT prettier configuration we are shipping to users with template.
This is repository root configuration to keep the whole repository formatted.
> Add root prettier configuration with the same settings as our `wasp` repo 

- .github/workflows/template-release.yml
Based on https://github.com/wasp-lang/wasp/pull/3196#discussion_r2398305684
Apparently I left some stuff unformatted earlier so it also has those formatting things
> Add note about template requirements
