wasp-lang/open-saas

- blog/astro.config.mjs
- blog/package-lock.json
- blog/package.json
- blog/src/components/MyHeader.astro
- blog/src/styles/tailwind.css
- blog/tailwind.config.mjs
- Setup Tailwind css for blogs and docs page
- Changed the theme for the docs/blogs page and tried to match it with the rest of the app.
Screenshots of the new docs/blog page:
Light Mode:
Dark Mode:
The colors do not match perfectly, and I needed help deciding the color palette for tailwind and starlight (added a comment for the same) @vincanger 
Addresses #7
> Theme docs/blogs with Tailwind

- app/main.wasp
- app/package-lock.json
- app/src/server/auth/social.ts
- blog/src/content/docs/general/admin-dashboard.md
- blog/src/content/docs/general/user-overview.md
- blog/src/content/docs/guides/analytics.md
- blog/src/content/docs/guides/authentication.md
- blog/src/content/docs/guides/authorization.md
- blog/src/content/docs/guides/deploying.md
- blog/src/content/docs/guides/email-sending.mdx
- blog/src/content/docs/guides/file-uploading.md
- blog/src/content/docs/guides/stripe-integration.md
- blog/src/content/docs/guides/stripe-testing.md
- blog/src/content/docs/index.md
- blog/src/content/docs/start/getting-started.md
- blog/src/content/docs/start/guided-tour.md
> Updates the deployed app to work with Wasp 0.13

- app/src/server/actions.ts
- Change to ensure that deleted and past_due subscriptions are not allowed to access the GPT API without credits.
> Fix: Updating subscription status check on generateGptResponse

- app/main.wasp
I did a bunch of small improvements to main.wasp and grouped them all in this one PR!
> main.wasp polish

- app/src/client/components/AppNavBar.tsx
The goal of this PR is to remove unnecessary  `sticky` class from `app/src/client/components/AppNavBar.tsx` due to already existing `absolute` positioning being set.
> Remove sticky positioning from AppNavBar

- opensaas-sh/blog/src/content/docs/start/guided-tour.md
- template/app/.gitignore
> addresses issue https://github.com/wasp-lang/open-saas/issues/152
> add customization checklist

- template/app/.env.server.example
- template/e2e-tests/README.md
instructed users to add `SKIP_EMAIL_VERIFICATION_IN_DEV=true` to `.env.server` before running local e2e tests to automatically verify the test user on signup
> add instructions for local e2e env vars

- opensaas-sh/blog/src/content/docs/guides/stripe-integration.md
A user on WSL encountered errors running the Stripe CLI: https://discord.com/channels/686873244791210014/1253545019785351180/1253951893877817527
The workaround was to append `sudo` to the commands as referenced in the GitHub issue (provided in the docs)
> Add note on `sudo` for Stripe CLI 

- template/app/main.wasp
- template/app/src/server/actions.ts
As discussed on Discord, change the default User entity ID to use a uuid instead of an int.
> Make the user entitiy use a uuid as its identifier

- opensaas-sh/blog/src/content/docs/general/admin-dashboard.md
- opensaas-sh/blog/src/content/docs/guides/analytics.md
in reference to this [discord convo](https://discord.com/channels/686873244791210014/1265391904472825966/1265721824596066335):
- updates the docs to let users know to switch to the google analytics provider utility functions within the `dailyStatsJob` if they want to use GA instead of Plausible. 
- adds more info about Wasp Jobs to docs
> add instructions about switching proivders in Job to google analytics

- template/app/package.json
Users reported:
```
[  Wasp !] npm error code ERESOLVE
[  Wasp !] npm error ERESOLVE could not resolve
[  Wasp !] npm error
[  Wasp !] npm error While resolving: openai@4.55.1
[  Wasp !] npm error Found: zod@3.22.4
[  Wasp !] npm error node_modules/zod
[  Wasp !] npm error   zod@"3.22.4" from the root project
[  Wasp !] npm error
[  Wasp !] npm error Could not resolve dependency:
[  Wasp !] npm error peerOptional zod@"^3.23.8" from openai@4.55.1
[  Wasp !] npm error node_modules/openai
[  Wasp !] npm error   openai@"^4.52.1" from the root project
[  Wasp !] npm error
[  Wasp !] npm error Conflicting peer dependency: zod@3.23.8
[  Wasp !] npm error node_modules/zod
[  Wasp !] npm error   peerOptional zod@"^3.23.8" from openai@4.55.1
[  Wasp !] npm error   node_modules/openai
[  Wasp !] npm …
```
> Use a version range for Zod dep

- template/app/src/payment/lemonSqueezy/paymentProcessor.ts
- template/app/src/payment/operations.ts
- template/app/src/payment/paymentProcessor.ts
- template/app/src/user/AccountPage.tsx
we had a user confused by the current console.log statement `User with ID 123... does not have a LemonSqueezy customer portal URL` so I removed the log and added a note to the file. I also changed a bit of the logic.
> improve logic for no lemon squeezy customer portal url

- MOST-ANNOYING-COOKIE-BANNER.md
Most Annoying Cookie Banner Submission: Glubker
Github Username: Glubker
**I recommend using this link instead as it seems to be more stable and faster than through StackBlitz:
[https://annoying-cookie-banner.vercel.app/](https://annoying-cookie-banner.vercel.app/)   (RECOMMENDED)**
––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––
Otherwise if needed, the StackBlitz url is below along with the source code, but it is recommended to use the Vercel link instead.
https://stackblitz.com/edit/github-gcme21?embed=1&file=src%2Flanding-page%2Fcomponents%2FHero.tsx&view=preview
> Most Annoying Cookie Banner Submission: Glubker

- opensaas-sh/blog/src/content/docs/guides/deploying.md
> Update deploying docs for clarity

- opensaas-sh/blog/src/content/docs/guides/email-sending.mdx
Old links for API Key and Domains have changed:
- Current Api key link leads to a 404
- Domain leads to a blank page
New links lead to the right pages:
- New API key link
- New domain link
> Update mailgun links for api keys and domains

- opensaas-sh/app_diff/src/admin/dashboards/analytics/AnalyticsDashboardPage.tsx.diff
- opensaas-sh/app_diff/src/analytics/providers/plausibleAnalyticsUtils.ts.diff
- It updated the Plausible API call to include imported data (old stats will be included)
- It sorts the sources tables
> opensaas.sh stats improvements

- opensaas-sh/app_diff/src/analytics/stats.ts.diff
- template/app/package.json
Fixes this issue: https://github.com/wasp-lang/wasp/issues/2464
We should merge this ASAP and make it part of the **0.15.0 tag**
> Adds tailwindcss as explicit dep

- opensaas-sh/blog/src/content/docs/start/getting-started.mdx
Updated the docs to include post-installation steps for WSL2 to ensure that database can run properly when `wasp start db` is run with WSL2. Similar to PR https://github.com/wasp-lang/wasp/pull/2452 in main Wasp repo. Related to issue #351.  
> Added post-installation WSL2 steps

- opensaas-sh/app_diff/src/payment/stripe/paymentProcessor.ts.diff
- opensaas-sh/blog/src/content/docs/guides/deploying.mdx
- template/app/src/payment/stripe/checkoutUtils.ts
- template/app/src/payment/stripe/paymentProcessor.ts
- template/app/src/payment/stripe/webhook.ts
- template/e2e-tests/tests/demoAppTests.spec.ts
- template/e2e-tests/tests/pricingPageTests.spec.ts
- template/e2e-tests/tests/utils.ts
Fixes #371 
Adds a new webhook event handler for `payment_intent.succeeded`. One-time payment products (i.e. "credits"), characterized by Stripe as having the `payment` mode (not the `subscription` mode), do not send an `invoice.paid` event (although subscriptions do), so we have to confirm payment and handle it better than just using the `checkout.session.completed` event, which can be sent even in the case that a payment fails.
> improve one-time payment webhook logic

- .github/workflows/e2e-tests.yml
- README.md
- opensaas-sh/blog/src/content/docs/start/getting-started.mdx
On the popular Open SaaS template, I updated the README to use the most up to date URL for installing Wasp :)
N/A
- [~] **Update e2e tests**: If you changed the [/template/app](/template/app), then make sure to do any neccessary updates to [/template/e2e-tests](/template/e2e-tests) also.
- [~] **Update demo app**: If you changed the [/template/app](/template/app), then make sure to do any neccessary updates to [/opensaas-sh/app_diff](/opensaas-sh/app_diff) also. Check [/opensaas-sh/README.md](/opensaas-sh/README.md) for details.
- [~] **Update docs**: If needed, update the [/opensaas-sh/blog/src/content/docs](/opensaas-sh/blog/src/content/docs).
> Update codebase to use the latest install WASP command

- opensaas-sh/blog/src/content/docs/guides/updating-opensaas.md
> Add guide on how to update a local Open SaaS app

- opensaas-sh/app_diff/src/client/components/NavBar/NavBar.tsx.diff
- opensaas-sh/app_diff/src/landing-page/contentSections.ts.diff
- template/app/src/client/components/NavBar/NavBar.tsx
This PR addresses and fixes issue #423 by implementing the following changes:
✅ Corrected the branding text in the top-left corner from "Open Saas" to "Open SaaS".
✅ Updated Jon Cocharan’s correct profile thumbnail to the team/contributors section.
✅ Included a working link to Jon Cocharan’s X.com (formerly Twitter) account.
> Fix typo in header branding and add Jon Cocharan’s profile image and X.com link

- .github/workflows/blog-deployment.yml
- opensaas-sh/blog/package-lock.json
- opensaas-sh/blog/package.json
- opensaas-sh/blog/public/llms-full.txt
- opensaas-sh/blog/public/llms.txt
- opensaas-sh/blog/scripts/generate-llm-files.mjs
- opensaas-sh/blog/src/components/HiddenLLMHelper.astro
- opensaas-sh/blog/src/content/docs/general/admin-dashboard.mdx
- opensaas-sh/blog/src/content/docs/general/user-overview.md
- opensaas-sh/blog/src/content/docs/guides/analytics.md
- opensaas-sh/blog/src/content/docs/guides/cookie-consent.mdx
- opensaas-sh/blog/src/content/docs/index.mdx
- opensaas-sh/blog/src/content/docs/start/getting-started.mdx
- opensaas-sh/blog/src/content/docs/start/guided-tour.md
**Users can now get llm-friendly versions of our docs at https://docs.opensaas.sh/llms.txt and/or https://docs.opensaas.sh/llms-full.txt.** (e.g. these urls can be added to cursor settings to include docs in context when mentioned)
Adds a script to generate llms.txt (which is kind of like a table of contents for LLM-friendly docs) and llms-full.txt which is all the doc files parsed and concatenated into an LLM-friendly format.
I also made some small adjustments to certain docs/guides to allow them to be parsed more easily/cleanly by the script. 
The script has also been added to the github workflow to run automatically
> add llms.txt & llms-full.txt script

- opensaas-sh/app_diff/main.wasp.diff
- template/app/main.wasp
Related to https://github.com/wasp-lang/wasp/pull/2625
> Adapt template and app to favicon breaking changes

- opensaas-sh/README.md
- opensaas-sh/tools/dope.sh
Fixes problems caused by:
> Aliases and functions do not propagate to shell scripts
Old alias instructions are removed, instead we "alias" the command inside of the script itself.
The script exits if there is no `gpatch` on MacOS.
Fixes #416
> Fix MacOS tools alias error 

- .github/workflows/blog-deployment.yml
- .github/workflows/e2e-tests.yml
- opensaas-sh/blog/public/llms-full.txt
- opensaas-sh/blog/src/content/docs/start/getting-started.mdx
- template/e2e-tests/package-lock.json
- template/e2e-tests/package.json
Fixes: https://github.com/wasp-lang/open-saas/issues/442
> Update minimum node version to 20

- template/app/src/demo-ai-app/operations.ts
> [Demo App] decrement credits only if user doesn't have subscription plan

- opensaas-sh/app_diff/fly-client.toml.diff
- opensaas-sh/app_diff/fly-server.toml.diff
- opensaas-sh/app_diff/package-lock.json.diff
We redeployed open saas after an outage. These are the new toml files.
> Update toml files for new deployment

- opensaas-sh/app_diff/main.wasp.diff
- opensaas-sh/app_diff/src/landing-page/components/Hero/Hero.tsx.diff
- opensaas-sh/app_diff/src/landing-page/contentSections.tsx.diff
- opensaas-sh/app_diff/src/shared/common.ts.diff
Fixes #478 
Simple one that updates the Open Graph and Twitter meta tags to include 'Built by Wasp' in the description. Updated the Hero section description to clarify the project as a starter kit and added attribution to Wasp with a link.
> Update Open SaaS meta tags and Hero description

- opensaas-sh/.gitignore
- opensaas-sh/tools/dope.sh
People who work on Open SaaS are often pained by `opensaas-sh/app/` folder being tracked.
By forcing the `opensaas-sh/app/` to be a separate git repository (via `git init`), we can:
1) Git ignore it
2) Have rest of diffing logic work (`git ls-files`) because there are no changes to git ignored files from the perspective of `opensaas-sh/app/`.
> Git ignore `opensaas-sh/app/` directory
